/* eslint-disable */
// Generated by Wrangler by running `wrangler types --env production --no-include-runtime` (hash: 31a9152358971c11b77a86c046de69bb)
interface __BaseEnv_Env {
	ASSETS: Fetcher;
	ENVIRONMENT: "production";
	API_HOST: "https://adfusion-backend-893008545922.asia-east1.run.app";
	INTERNAL_KEY: string;
	JWT_SECRET: string;
	PAGESPEED_API_KEY: string;
	PHP_SERVICE_AUTH_SECRET: string;
	WORKER_SELF_REFERENCE: Service<typeof import("./.open-next/worker").default>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./.open-next/worker");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ENVIRONMENT" | "API_HOST" | "INTERNAL_KEY" | "JWT_SECRET" | "PAGESPEED_API_KEY" | "PHP_SERVICE_AUTH_SECRET">> {}
}
